# https://groups.community.sap.com/t5/application-development/sap-developer-challenge-apis-task-0-learn-to-share-your-task/m-p/276058
# https://developer-challenge.cfapps.eu10.hana.ondemand.com

@endpoint=https://developer-challenge.cfapps.eu10.hana.ondemand.com
@hashpath={{endpoint}}/v1/hash

@uaa_url=
@clientId=
@clientSecret=

@userEmail=<email>
@userPassword=<password>

@communityid=johna69
@value='12'

### Get Hash
GET {{hashpath}}(value={{value}})
Accept: */*
CommunityID: {{communityid}}

### Get Token Client Credentials
# @name authResponse
POST {{uaa_url}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Accept: */*

grant_type=client_credentials
&response_type=token
&client_id={{clientId}}
&client_secret={{clientSecret}}

### Get Token Client Credentials
# @name authResponse
POST {{uaa_url}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Accept: */*

grant_type=password
&response_type=token
&client_id={{clientId}}
&client_secret={{clientSecret}}
&username={{userEmail}}
&password={{userPassword}}