# https://groups.community.sap.com/t5/application-development/sap-developer-challenge-apis-task-0-learn-to-share-your-task/m-p/276058
# https://developer-challenge.cfapps.eu10.hana.ondemand.com

@endpoint=https://developer-challenge.cfapps.eu10.hana.ondemand.com
@hashpath={{endpoint}}/v1/hash

@value='this-is-the-year-of-the-api'

###
GET {{hashpath}}(value={{value}})
Accept: */*
CommunityID: johnastill

